modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/cech12/UsefulHats/issues"
[[mods]]
    modId="usefulhats"
    version="${file.jarVersion}"
    displayName="Useful Hats"
    displayURL="https://github.com/cech12/UsefulHats"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds some useful hats.
    '''